### PR TITLE
Page redesign

### PR DESCRIPTION
**Pull request by bidoggia**
Hi! I redesigned the page so it looks more awesome than ever before!

### CODE REVIEW

**Comment by Araraura** [comment]
Thanks for the redesign, however I don't think I can merge it because this is too different from the type of design I'm aiming for. I want the website to look clean and simple, and this redesign is going against it. Too many colors, and it's hard to read some of the text because it slightly blends with the background.

Though, I'll probably take a page from your book and center the credits text if that's alright with you. Sorry I couldn't merge this after all that work.

**Comment by bidoggia** [comment]
No worries, I understand your point. If you find it better I could maybe change the background image or even completely remove it, but keep other changes if you like them. I made some changes and it looks like this now.
image
I hope you like it, but I will totally understand if you don't proceed with them.
Thank you for your attention, 
DarthWynaut.

**Comment by Araraura** [comment]
> No worries, I understand your point. If you find it better I could maybe change the background image or even completely remove it, but keep other changes if you like them. I made some changes and it looks like this now. image I hope you like it, but I will totally understand if you don't proceed with them. Thank you for your attention, DarthWynaut.

Hmm, I could probably go with the font as well... I'll try to get another look at this tomorrow and see what I'd like to keep or change.

**Comment by Araraura** [comment]
After considering it some more I've decided to just stick with the current design. Sorry again for rejecting it but I want to keep the design of the website simple and more readable and stick with the current fonts.

**Comment by bidoggia** [comment]
No problem! Thank you for your attention and considering the changes anyways.

**Pull request closed without merging**
